action update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,6 +34,20 @@ jobs:
       - name: Push to ECR 
         run: sudo docker push ${ECR_REGISTRY}/${ECR_REPO}:${APP_VERSION}
 
+    
+  checkvulns:
+    name: Check Vulns 
+    needs: build
+    runs-on: xentrail
+    steps:
+      - name: Check if there are critical vulns in the docker image 
+        run: |
+          IMAGE_DIGEST=$(aws --region ${AWS_REGION} ecr describe-images --repository-name ${ECR_REPO} --image-ids imageTag=${APP_VERSION} --query imageDetails[0].imageDigest)
+          FINDINGS=$(aws --region ${AWS_REGION} ecr describe-image-scan-findings  --repository-name ${ECR_REPO} --image-id imageDigest=${IMAGE_DIGEST})
+          HIGH_FINDINGS=$(echo $FINDINGS | jq '.imageScanFindings.findingSeverityCounts.HIGH')
+          CRITICAL_FINDINGS=$(echo $FINDINGS | jq '.imageScanFindings.findingSeverityCounts.CRITICAL')
+          if [ -n ${CRITICAL_FINDINGS} ]; then echo "No Critical Vulns found. Fix High Vulns if there are anoy. Found ${HIGH_FINDINGS}" High Vulnerabilities in this Image. ;else echo "Failing Pipeline as Critical Vulnerabilities found " && exit 1; fi 
+       
 
   deploy:
     name: Deploy to k8s
