action update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,7 +35,7 @@ jobs:
         run: sudo docker push ${ECR_REGISTRY}/${ECR_REPO}:${APP_VERSION}
     
   checkvulns:
-    name: Check VUlns 
+    name: Check Vulns 
     needs: build
     runs-on: xentrail
     steps:
@@ -43,9 +43,9 @@ jobs:
         run: |
           IMAGE_DIGEST=$(aws --region ${AWS_REGION} ecr describe-images --repository-name ${ECR_REPO} --image-ids imageTag=${APP_VERSION} --query imageDetails[0].imageDigest)
           FINDINGS=$(aws --region ${AWS_REGION} ecr describe-image-scan-findings  --repository-name ${ECR_REPO} --image-id imageDigest=${IMAGE_DIGEST})
-          MEDIUM_FINDINGS=$(echo $FINDINGS | jq '.imageScanFindings.findingSeverityCounts.MEDIUM')
+          HIGH_FINDINGS=$(echo $FINDINGS | jq '.imageScanFindings.findingSeverityCounts.HIGH')
           CRITICAL_FINDINGS=$(echo $FINDINGS | jq '.imageScanFindings.findingSeverityCounts.CRITICAL')
-          if [ -n ${CRITICAL_FINDINGS} ]; then echo "No Critical Vulns found. Medium Vulns: ${MEDIUM_FINDINGS}" ;else echo "Failing Pipeline as Critical Vulnerabilities found " && exit 1; fi 
+          if [ -n ${CRITICAL_FINDINGS} ]; then echo "No Critical Vulns found. Fix High Vulns if there are anoy. Found ${HIGH_FINDINGS}" High Vulnerabilities in this Image. ;else echo "Failing Pipeline as Critical Vulnerabilities found " && exit 1; fi 
 
   deploy:
     name: Deploy to k8s
